name: steam-eye

services:
  postgres:
    image: postgres:17
    container_name: steam-eye-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - steam-eye-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  steam-eye-postgres-data:
